name = "ExtendableGrids"
uuid = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>", "Christian Merdon  <christian.merdon@wias-berlin.de>", "Johannes Taraz  <johannes.taraz@gmail.com>"]
version = "1.6.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[extensions]
ExtendableGridsGmshExt = "Gmsh"
ExtendableGridsTetGenExt = "TetGen"
ExtendableGridsTriangulateExt = "Triangulate"

[compat]
AbstractTrees = "0.3,0.4"
Bijections = "0.1.4"
Dates = "1.6"
DocStringExtensions = "0.8,0.9"
ElasticArrays = "1"
Gmsh = "0.2.2,0.3"
InteractiveUtils = "1.6"
LinearAlgebra = "1.6"
Printf = "1.6"
Random = "1.6"
SparseArrays = "1.6"
StaticArrays = "1"
StatsBase = "0.34"
TetGen = "1.5.1"
Triangulate = "2.3.2"
UUIDs = "1.6"
WriteVTK = "1.14"
julia = "1.9"
